# Generated by Django 3.2.7 on 2022-10-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rakusuke_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_do', models.TextField(max_length=40, verbose_name='やるべきこと')),
                ('schedule_priority', models.IntegerField(default=2, max_length=1, verbose_name='優先度')),
                ('schedule_start_date', models.DateTimeField(auto_now=True, verbose_name='開始日時')),
                ('schedule_end_date', models.DateTimeField(auto_now=True, verbose_name='終了日時')),
                ('schedule_start_hour', models.DateTimeField(default=0, verbose_name='開始日時(時)')),
                ('schedule_start_min', models.DateTimeField(default=0, verbose_name='開始日時(分)')),
                ('schedule_end_hour', models.DateTimeField(default=0, verbose_name='終了日時(時)')),
                ('schedule_end_min', models.DateTimeField(default=0, verbose_name='終了日時(分)')),
                ('schedule_worktime', models.IntegerField(max_length=3, verbose_name='一日の作業時間')),
                ('sucedule_creation_stage', models.IntegerField(max_length=3, verbose_name='作成段階')),
            ],
            options={
                'verbose_name_plural': 'rakusuke_schedule',
            },
        ),
    ]
